### ISSUE TITLE
Methods for upgrading Models and Serving Runtimes

### ISSUE THREAD

**Issue by Jooho** [opendatahub-io/kserve#40] opened 2023-07-26 15:39 UTC
/kind doc

There are mainly 2 upgrade scenarios for models.
- ServingRuntime upgrade
- Model Upgrade

For the first scenario, it will use deployment rolling upgrade but for the second one, it is not obvious yet.  As a user, specific flows are needed for upgrading their model.

**Comment by bdattoma** [comment] 2023-07-26 16:16
Some thoughts/question

- does the serving runtime automatically restarts any deployment after an edit to ServingRuntime object? (e.g., hw limit/request, image url)
- would it be possible to a have an option to set the runtime upgrade to manual  vs auto?
- will a new version of the runtime have also a different ServingRuntime name? InferenceService objects are tide to a specifc runtime name
- how would the runtime object react to a change in the inference service object? (e.g., model path)

**Comment by israel-hdez** [comment] 2023-09-06 01:20
Trying to answer your questions @bdattoma :

>     * does the serving runtime automatically restarts any deployment after an edit to ServingRuntime object? (e.g., hw limit/request, image url)
> 

No. The deployments are updated on the next reconciliation of the InferenceService; either by editing the `isvc` or by kserve-controller restart.

>     * would it be possible to a have an option to set the runtime upgrade to manual  vs auto?
> 

Do you mean something to be able to edit the ServingRuntime without affecting current deployments?

To me, the `ServingRuntime` -> `InferenceService` relationship is similar to a `ConfigMap` -> `Deployment`. If you change the `ConfigMap` running pods are unaffected until you restart them (even without changing the Deployment). Similarly, if you change the ServingRuntime, already running Deployments are unaffected until something triggers a reconciliation (even without changing the InferenceService).

Not sure if my previous paragraph contributes to some answer. If not, I'm seeking for more details in the question.

>     * will a new version of the runtime have also a different ServingRuntime name? InferenceService objects are tide to a specifc runtime name
> 

Perhaps, as Jooho mentioned in the main description, this is more of user workflow that needs to be documented.

>     * how would the runtime object react to a change in the inference service object? (e.g., model path)

Any change in the InferenceService creates a new deployment. The old one, apparently, is removed once the new one becomes _ready_ as indicated by readiness/health probes. KNative controls this lifecycle.

**Comment by israel-hdez** [comment] 2023-09-06 17:56
@bdattoma Yes, the workflow is not fully clear at the moment. I agree that we need to involve PM here.

Thanks for the follow up!

**Comment by israel-hdez** [comment] 2023-09-13 00:24
Still in progress.

This ticket will slip to the next sprint, as I'm still gathering information.
I'll give an update next week's Tue 19th.

**Comment by israel-hdez** [comment] 2023-09-18 22:16
There are different perspectives for upgrades.

From an technical API perspective: when editing an existing `InferenceService` or `ServingRuntime` resource, the expected behavior should adhere to the [Kubernetes's declarative API description](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#declarative-apis). The relevant point is:

> "_The objects define configuration of applications or infrastructure._" 

which implies that serving should configure the cluster as close as possible to the desired configuration. This means that there is a technical gap around `ServingRuntime`, because edits to SRs are not applied unless some other event triggers/forces an update.

Any additional requirement around an upgrade (perhaps, zero down-time) was not part of the discussion, but it could be treated as implementation detail of the upgrade (if needed).

When the front-end is involved in the previous process of editing an `InferenceService` or `ServingRuntime`, then the UI should warn the user about the impact of the edit. If the user proceeds, then edits to resources are done and changes are applied. No controls for triggering manual/automatic upgrades need to be provided in the UI. So, the UI just provides the additional benefit of a warning and, past that, the rest is the typical K8S declarative-API behavior.

On top of the technical API, we just give recommendations (best-practices):

* Upgrading a model should not be done by editing an `InfrenceService`, but creating a new one and gradually move dependent apps to the new version. This would give the user control over the upgrade process.
* Same case for `ServingRuntimes`: upgrading the version on the runtime should be done by creating a new `ServingRuntime`, rather than editing the existing one. Existing models should be associated to a specific runtime (rather than auto-selection). This way, the user can gradually move `InferenceServices` from the old runtime to the new one, giving the needed control over the upgrade process.

Generally speaking, the upgrade intent must be explicit.

Abstracting implementation details, and using front-end terminology, the user is expected to have two model deployments: one with the older version, and one with the newer. User apps need to be changed to use the endpoint of the new model. Similarly, for the model-server, users are expected to create two, and models are manually re-associated with the new server. The mechanisms to support these workflows are open for technical discussion.

That said, it is expected that version management is done through the Model Registry. So, any enhancements to the current front-end to support the upgrade workflow should remain minimal, while the model registry evolves (cc @dhirajsb)

**Comment by israel-hdez** [comment] 2023-09-25 23:38
I'll close this issue as done, hoping that my last comment is the expected outcome.

In general, the suggested way for upgrades is by creating new resources and gradually move applications to the newly deployed versions to, later, downscale the older versions.

**Closed by israel-hdez** 2023-09-25 23:38 UTC
Labels: kind/documentation
